- job:
    name: ansible-role-logrotate
    run: tests/playbooks/run.yaml
    roles:
      - zuul: openstack/ansible-role-logrotate

- job:
    name: ansible-role-logrotate-fedora-latest
    parent: ansible-role-logrotate
    nodeset: fedora-latest

- job:
    name: ansible-role-logrotate-ubuntu-bionic
    parent: ansible-role-logrotate
    nodeset: ubuntu-bionic

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
    check:
      jobs:
        - ansible-role-logrotate-fedora-latest
        - ansible-role-logrotate-ubuntu-bionic
        - tox-linters
    gate:
      jobs:
        - ansible-role-logrotate-fedora-latest
        - ansible-role-logrotate-ubuntu-bionic
        - tox-linters
